logfile: ""
past: true
reg:
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\] (OnPlayerJoined .*)'
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\] (OnPlayerLeft .*)'
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\] (Joining wrld.*)'
