logfile: ""
past: true
reg:
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\[NetworkManager\] (OnPlayerJoined .*)'
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\[NetworkManager\] (OnPlayerLeft .*)'
  - '([0-9]{4}\.[0-9]{2}\.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).*?\[RoomManager\] (Joining wrld.*)'
